### ISSUE TITLE
Error when I tried to install chromium with a family link account

### ISSUE THREAD

**Issue by Purpleman666** [FydeOS/chromium_os-raspberry_pi#47] opened 2019-12-22 23:42 UTC
Hello guys, 

Thank you for your awsome work.
I've tried to install chromium r77r2 on a raspberry 4. I's perfect with a normal account, but it don't work if you tried with a google family link account. It begin well, but at the end it encounted an error, and it says that i have to do it another time. I tried with another family link account it's the same thing.

**Comment by faizhasim** [comment] 2020-03-29 11:34
I encounter same issue. I am suspecting family link won't be supported. 

Regardless, work around is, you can use guess account - although that's definitely lack personalisation.

**Comment by dawithers** [comment] 2020-04-24 01:09
Cloudready has the same issue and they say it's because it requires a TPM chip to be available in the device, which obviously this doesn't have. So it may not even be possible.

https://neverware.zendesk.com/hc/en-us/community/posts/206761367-Unable-to-create-Supervised-User

**Comment by SidShetye** [comment] 2020-04-24 07:32
If that’s confirmed to be the case, then the TPM’s just a device. Can be emulated to workaround this issue. In fact, there are a couple of projects. First google hit https://github.com/PeterHuewe/tpm-emulator ... I wish I had the time to investigate myself but seems like a fun project.

**Closed** 2020-12-12 15:29 UTC
